# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

from Fibonacci import fiboMenorA

def esPar(num):
	return num % 2 == 0

n = int(input("Fibonacci menor a: "))
fibonacci_menor_a = fiboMenorA(n) 

fibonacci_menor_a_pares = []

for numero in fibonacci_menor_a:
	if esPar(numero): 
		fibonacci_menor_a_pares.append(numero)	

print(sum(fibonacci_menor_a_pares))